version: '3.9'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: django_app
    volumes:
      - ../:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
    networks:
      - noticias_net
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  celery:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: celery_worker
    command: celery -A noticias_project worker --loglevel=info
    volumes:
      - ../:/app
    depends_on:
      - redis
      - db
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
    networks:
      - noticias_net

  redis:
    image: redis:7
    container_name: redis_broker
    ports:
      - "6379:6379"
    networks:
      - noticias_net

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - noticias_net
  
  # flower:
  #   image: mher/flower
  #   container_name: flower_dashboard
  #   working_dir: /app
  #   volumes:
  #     - ../:/app
  #   command: celery -A noticias_project flower --port=5555 --broker=redis://redis:6379/0
  #   ports:
  #     - "5555:5555"
  #   depends_on:
  #     - redis
  #     - celery
  #   networks:
  #     - noticias_net

  flower:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: flower_dashboard
    working_dir: /app
    command: celery -A noticias_project flower --port=5555 --broker=redis://redis:6379/0
    ports:
      - "5555:5555"
    volumes:
      - ../:/app
    depends_on:
      - redis
      - celery
    networks:
      - noticias_net



volumes:
  pgdata:

networks:
  noticias_net:
    driver: bridge
